#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroid.Resource", IsApplication=true)]

namespace XamarinAndroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accentColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int darkColor = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int lightColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int primaryColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int primaryColorAlt = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int secondaryColor = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int secondaryColorAlt = 2130771974;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int circle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int computer = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int gradient = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int logotype_grey = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int logotype_white = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int welcome = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnLoginForgotPassword = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnLoginUser = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int edittextLoginName = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int edittextLoginPassword = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int linearlayoutCustomRow = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int lsCatalogCustom = 2130903045;
			
			// aapt resource value: 0x7F030007
			public const int txtCampaignCategory = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int txtCampaignDateDay = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int txtCampaignDateMonth = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int txtCampaignDescription = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int txtCampaignName = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int txtCampaignSubscribers = 2130903052;
			
			// aapt resource value: 0x7F030006
			public const int txtCampaigSubscribersTitle = 2130903046;
			
			// aapt resource value: 0x7F03000D
			public const int txtItemSubtitle = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int txtItemTitle = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int txtLoginName = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int txtLoginPassword = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int txtLoginSlogan = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int viewSolid = 2130903058;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Campaign = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Catalog = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int CustomListRow = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Login = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int applicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int btnLoginForgotPassword = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int btnLoginUser = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int dlgForgotContent = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int dlgForgotTitle = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int dlgNegativeButton = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int dlgOutgoingLink = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int dlgPositiveButton = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int isActiveFalse = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int isActiveTrue = 2131034121;
			
			// aapt resource value: 0x7F05000B
			public const int txtCampaignClicksTitle = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int txtCampaignDateTitle = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int txtCampaignIsActiveTitle = 2131034125;
			
			// aapt resource value: 0x7F05000A
			public const int txtCampaigSubscribersTitle = 2131034122;
			
			// aapt resource value: 0x7F05000E
			public const int txtItemSubtitle = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int txtItemTitle = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int txtLoginName = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int txtLoginPassword = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int txtLoginSlogan = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060001
			public const int campaignActivity = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int customListRow = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int layoutDate = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int layoutSubscribers = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int loginActivity = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int loginButton = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int loginForgot = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int loginInput = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int loginLabel = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int loginSlogan = 2131099658;
			
			// aapt resource value: 0x7F060000
			public const int Marvelous = 2131099648;
			
			// aapt resource value: 0x7F06000B
			public const int txtCampaignCategory = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int txtCampaignContent = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int txtCampaignDescription = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int txtCampaignName = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int txtCampaignSubtitle = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int txtItemSubtitle = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int txtItemTitle = 2131099665;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
